project_id = "ulzeeekfkgdhoojbiioo"

[functions.evolution-qrcode]
verify_jwt = false

[functions.evolution-fetch-chats]
verify_jwt = false

[functions.evolution-fetch-messages]
verify_jwt = false

[functions.evolution-send-message]
verify_jwt = false

[functions.evolution-check-status]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.get-users-status]
verify_jwt = false

[functions.toggle-user-status]
verify_jwt = false

[functions.evolution-send-media]
verify_jwt = false

[functions.evolution-fetch-media-base64]
verify_jwt = false
